#!/usr/bin/env bash

set -e

PID="$$"

################
# Pillar Code
PID_PATH='/tmp/pillar'
PID_FILE="$PID_PATH/pillar.$PID.pid"

# Create Pid file
echo $! > "$PID_PATH/pillar.$PID.pid";

# Cleanup Pid file on exit
function onExit {
  rm -f $PID_FILE
}
trap onExit EXIT
################


################
# Actual Worker Code
echo "bash $MY_ENV"
while [ true ]
do
    EPOCH=$(date +%s)
    echo "DEBUG -- Checkin: $PID $EPOCH" >> /tmp/print-time.log;
    sleep 5;
done