#!/usr/bin/env ruby

require 'pillar'
# require 'childprocess'
require 'net/http'
require 'json'

# payload = {
#   worker_id: SecureRandom.uuid,
#   name: "worker-#{Pillar.epoch}",
#   args: "Do something with this please."
# }.to_json

# puts payload
Pillar.configure do |config|
end

# host = Pillar.configuration.hosts.sample
# payload = Pillar::Worker.new(
#   args: ['/git/pillar/scripts/print-time', ''], 
#   env: {"MY_ENV" => '/tmp/dump/blah'}
# )


payload = Pillar::Worker.new(
  args: ['/git/pillar/examples/print-time', ''], 
  env: {"MY_ENV" => '/tmp/dump/blah'}
)

# `curl -X POST -H "application/json" -d '#{payload}' #{host}/workers`
# uri = URI.parse("http://#{host}:4567/workers")
# puts Net::HTTP.post_form(uri, {worker: payload}).response
# puts Net::HTTP.post_form(uri, payload.to_json).response

# puts Pillar::Worker.new.inspect
# params = { args: ['/location/of/my/script', '--arg==32'], env: {MY_ENV: '/tmp/dump'} }
# wrk = Pillar::Worker.new params
# puts wrk.to_json
# puts JSON.parse wrk.to_json
# puts (Pillar::Serialization.from_json wrk.to_json).inspect

# payload.spawn
puts payload.to_json