#!/usr/bin/env ruby

require 'pillar'

Pillar.client_setup

logger = Logger.new('/tmp/print-time.log')

puts ENV['MY_ENV']

loop do
  logger.debug "Checkin: #{Process.pid} #{Pillar.epoch}"
  sleep 5
end